// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuRNU7pcMFY1MP-oOouZHDV1torwNTLPw',
    appId: '1:292124129307:web:930e90386e5fb5d8f9a0be',
    messagingSenderId: '292124129307',
    projectId: 'ellemora-fashions',
    authDomain: 'ellemora-fashions.firebaseapp.com',
    storageBucket: 'ellemora-fashions.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCETM2hPaswLpbWMum9iqxUQu-KZBIk8NU',
    appId: '1:292124129307:android:067ec1e2d73ac6dcf9a0be',
    messagingSenderId: '292124129307',
    projectId: 'ellemora-fashions',
    storageBucket: 'ellemora-fashions.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj_EJ5HHRYF-aKUAsPHhxRm5Jb4-SDPmU',
    appId: '1:292124129307:ios:68a4b24e2185f3abf9a0be',
    messagingSenderId: '292124129307',
    projectId: 'ellemora-fashions',
    storageBucket: 'ellemora-fashions.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj_EJ5HHRYF-aKUAsPHhxRm5Jb4-SDPmU',
    appId: '1:292124129307:ios:68a4b24e2185f3abf9a0be',
    messagingSenderId: '292124129307',
    projectId: 'ellemora-fashions',
    storageBucket: 'ellemora-fashions.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuRNU7pcMFY1MP-oOouZHDV1torwNTLPw',
    appId: '1:292124129307:web:dd3126589a441d53f9a0be',
    messagingSenderId: '292124129307',
    projectId: 'ellemora-fashions',
    authDomain: 'ellemora-fashions.firebaseapp.com',
    storageBucket: 'ellemora-fashions.appspot.com',
  );

}